---
all:
  children:
    caddy:
      hosts:
        rpi:
        vps:
    proxmox:
      hosts:
        samba_share:
        mediacenter:
        docker_pve:
        docker_pve2:
    proxmox_hosts:
      hosts:
        pve:
        pve2:
    laptop:
      hosts:
        ph16-71: